* USB C Power Cables

Using cheap USB PD sinks from AliExpress it is possible to add USB C
to a lot of old appliances. I plan to add it by cutting a hole in the chassis of the device at hand and using hot glue to secure the board in the device

I plan on:

- Making a modified 9 V battery with USB C on the bottom to use with component
  tester.
- Adding a USB C connector to:
  - My Baofeng UV-5R radio charger (the original charger supplies 10V, I plan on a 9V USB C Sink, the internal regulator should have no problem with that
  - My Brother PTOUCH labeler
  - Using a PD Trigger in order to supply my TS-80 soldering iron with sufficient power from a USB PD source instead of the Quickcharge 3.0 that it uses

I ordered 4 sinks. 2 fixed 9 V sinks, a variable one with screw terminal blocks and a variable one with a USB A port. For the first two projects I plan to use the fixed modules, for the TS-80 I plan to use the USB A one with a standard USB A to USB C cable.

** Battery

I already have the battery tore down. When I receive the USB sink I can
proceed to assemble the final product. Hot glue should be fine for
structure. Two wires will then connect the sink to the battery terminals.

** Notes

It would be probably nice to seal sinks that I plan to handle and keep out of enclosures with heat shrink tube.
